version: "3"
  
services:
  node-app:
    build: .
    ports:
      - "8080:8080"
    environment: 
      - PORT=8080
    depends_on:
      - mongo

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: hawk
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-db:/data/db
  redis:
    image: redis:7-alpine
volumes:
  mongo-db:
