version: "3"
services:
  node-app: 
    build: .
    ports:
      - "8080:8080"
    volumes: 
      - ./:/app:ro
      - /app/node_modules
    environment: 
      - PORT=8080
        #env_file:
        #- ./.env
