version: "3"
services:
  nginx:
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  node-app:
    build:
      context: .
      args: 
        NODE_ENV: development
    volumes:
      - ./:/app:ro
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=8080
      - MONGO_USER=hawk
      - MONGO_PASSWORD=example
      - SESSION_SECRET=secret

    command: npm run dev

  mongo:
    environment:
      MONGO_INITDB_ROOT_USERNAME: hawk
      MONGO_INITDB_ROOT_PASSWORD: example
